### PR TITLE
fix re-running buildout with merge without sha

### PR DESCRIPTION
**Pull request by lepistone**
Addresses anybox/anybox.recipe.odoo#46

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by nbessi** [comment]
We already merge this in our base buildout config un test and prod profile.
I agreed with @guewen that we should not put this applicable for dev profile.
:-1:

**Comment by nbessi** [comment]
@lepistone that said there is only the vc-clear-retry command https://github.com/camptocamp/base_odoo_config/blob/8.0/profiles/prod.cfg#L21https://github.com/camptocamp/base_odoo_config/blob/8.0/profiles/test.cfg#L21

**Comment by lepistone** [comment]
Right @nbessi, thanks for the heads-up. So what about if I put the two options in prod, test, and travis, too?

**Comment by guewen** [comment]
I close this as you proposed base_odoo_config#28

**Pull request closed without merging**
